repos:
  # sort imports 
  - repo: https://github.com/pycqa/isort 
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  # format all code using black
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9
  # apply black formatting to code within docstrings
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
  # apply flake8 checks to code
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
